### ISSUE TITLE
How flexible is this lib?

### ISSUE THREAD

**Issue by Mauker1** [thellmund/Android-Week-View#17]
I have a question about this lib.

I'm working on an app that has a calendar feature, but instead of working on a "weekly fashion", it's supposed to display day by day, but here's the catch: It's supposed to do that for multiple people.

So instead of having the days of the week on the columns, I would have to display user names and pictures, and each row would correspond to their daily schedules.

Is is possible to use this lib on this scenario? Or is it too tied to displaying only the days of the week?

**Comment by Bwaim** [comment]
Hi @Mauker1, you can change the label of columns and rows but it's related to days and hours.
What i mean is for example, instead of displaying "Mon" in the date formatter you can return "John".
Moreover, actually, you can't display image.
Finally, when creating events, you should trick the library giving fake date for the events.

For me it seems quite difficult to use this library to do what you want, or you will have to adapt it to your needs.

**Comment by Mauker1** [comment]
Thank you for your quick response!

It seems a fork and adaptation would be the best approach then. But your idea could work as well, although without images (which is not critical).
