### ISSUE TITLE
Display event location under title if enough space

### ISSUE THREAD

**Issue by thellmund** [thellmund/Android-Week-View#21]
The event location is currently displayed right after the event title. Instead (or maybe as another option?), it should be possible to display it _below_ the event title, provided that there is enough space.

**Comment by tylermarien** [comment]
It would be nice to be able to format the title and/or location however we wanted. If they were of type CharSequence (instead of String) then we could pass a Spanned with our own custom formatting to them. Another option (that might be a little more backwards compatible) would be to add another field to WeekViewEvent which was a CharSequence (maybe something called description). Then we could pass empty strings to title and location, and a formatted string to this new field.

Another option would be to allow custom EventChip classes (as mentioned in another issue) that would allow custom styling of the entire EventChip.
