### ISSUE TITLE
ANR after zooming week view

### ISSUE THREAD

**Issue by HuuNguyen312** [thellmund/Android-Week-View#247]
**Describe the bug**
ANR after zooming week view

**To Reproduce**
1. Create an event with a duration <10 minutes
2. Zoom in/out
3. ANR

**Comment by MatijaSokol** [comment]
I have same problem. When trying to **zoom in/zoom out** multiple times, ANR dialog opens. Also, like @HuuNguyen312, this bug happens when events in calendar are not very long (I reproduce this bug with tasks duration of **10 and 20 minutes**).  

**From Logcat:**
Background concurrent copying GC freed 177266(7MB) AllocSpace objects, 0(0B) LOS objects, 41% free, 8MB/14MB, paused 567us total 102.436ms

This message is showing until application is forced closed.

Here is app screenshot when trying to zoom in/zoom out.
![calendar](https://user-images.githubusercontent.com/47254313/116898665-f4c9a800-ac36-11eb-8298-34814dd1c967.jpg)

**Comment by thellmund** [comment]
I can’t reproduce the issue on my device. What emulator or device are you using?

**Comment by MatijaSokol** [comment]
I reproduce bug with both Samsung Galaxy S7 Edge and Xiaomi Redmi 6. Also, my colleague reproduced bug with newer Samsung.

Can you try inserting >10 short tasks that are visible at the same time and zoom in/zoom out for some time?

**Comment by HuuNguyen312** [comment]
I reproduce this bug with all devices of my company: Samsung S10+, Note 8, Note 20, Xiaomi, Oppo, Nokia, etc

**Comment by thellmund** [comment]
Can you give some more information such as the OS version and your WeekView configuration?

**Comment by MatijaSokol** [comment]
Samsung Galaxy S7 Edge: Android 8
Xiaomi Redmi 6: Android 10

In my app, WeekView is inside Fragment (using NavComponents). My adapter is extending WeekViewSimpleAdapterJodaTime. Here is WeekView configuration from XML:

![image](https://user-images.githubusercontent.com/47254313/121890571-cac9d200-cd1a-11eb-94e5-2f432443f55d.png)

**Comment by thellmund** [comment]
Ok, able to reproduce it now. I pushed a fix in c6a460ca735f1b37cc8369fa532f900bb35fe8ab and will create a new release soon.

**Comment by thellmund** [comment]
Release is out. Closing this now, but let me know if anything else doesn’t work as expected.
