### ISSUE TITLE
Allow use of jsr310 types in API

### ISSUE THREAD

**Issue by jcogilvie** [thellmund/Android-Week-View#69]
Currently the builders use Calendar instances, which are not great to work with.  I can see that internally they immediately convert to jsr310 objects.  If you could expose those objects on the builder it would be helpful for cleaning up my APIs.  Ditto providing a month change listener that takes those types.

**Comment by thellmund** [comment]
I agree that using `Calendar` is a pain. I used `ThreeTenABP` for internal date manipulation in the library, but have removed it for the upcoming version 4, because I don’t want a dependency on another library and because it caused issues with the live preview in Android Studio. 

Here’s how I plan to proceed: While the main library stays free of third-party libraries, I will publish extension libraries for the common date libraries (`ThreeTenABP`, `JodaTime`, the Java 8 Date API). They will include overloaded `setMonthChangeListener()` methods, e.g.

```kotlin
fun <T> WeekView<T>.setOnMonthChangeListener(
    block: (startDate: LocalDate, endDate: LocalDate) -> List<WeekViewDisplayable<T>>
) {
    onMonthChangeListener = object : OnMonthChangeListener<T> {
        override fun onMonthChange(
            startDate: Calendar,
            endDate: Calendar
        ): List<WeekViewDisplayable<T>> = block(startDate.toLocalDate(), endDate.toLocalDate())
    }
}
```
This way, I can avoid adding all third-party libraries to the main `WeekView` library, but still allow the usage. What do you think?

**Comment by tlozovyi** [comment]
Sounds great.
I use JodaTime in most cases and removing conversions to Calendar and back would be super nice.

**Comment by jcogilvie** [comment]
That's a great idea.

**Comment by thellmund** [comment]
The extension modules are now in the `develop` branch and will be included in the next release. Closing this issue now, but feel free to re-open if you discover any issues.
